### ISSUE TITLE
Adding firewall to a droplet

### ISSUE THREAD

**Issue by Lvl4Sword** [ansible-collections/community.digitalocean#159]
##### SUMMARY
I'm not actually sure if this is a documentation issue or the collection actually doesn't have it.
Trying to add a firewall to a droplet using latest ( 1.9.0 ) of the collection. There doesn't actually seem to be anything within ``firewall`` or ``firewall_info`` that I've seen.

##### ISSUE TYPE
- Documentation Report?

##### COMPONENT NAME
``firewall`` / ``firewall_info``

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

**Comment by tadeboro** [comment]
https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_firewall_module.html#ansible-collections-community-digitalocean-digital-ocean-firewall-module and https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_firewall_info_module.html#ansible-collections-community-digitalocean-digital-ocean-firewall-info-module are not working for you?

**Comment by Lvl4Sword** [comment]
https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_firewall_module.html#ansible-collections-community-digitalocean-digital-ocean-firewall-module seems to only be for adding/managing a firewall rule. If I already have a saved firewall, that page doesn't convey a saved firewall can also be added to a droplet.

**Comment by tadeboro** [comment]
Ugh, you are right; connecting droplets to existing firewalls is really awkward to do using DO modules because you need to list droplet ids in the firewall specification. It would be more natural (and what we usually do when designing cloud collections) if droplets contained information about the firewalls that apply to them. But I guess the current implementation was easier since it mimics how the DO API is structured.

That being said, you can probably do something like this to connect a droplet and a firewall:

- name: Retrieve firewall info
  community.digitalocean.digital_ocean_firewall_info:
    name: my_firewall
  register: firewall_data

- name: Add droplet to firewall
  community.digitalocean.digital_ocean_firewall:
    name: "{{ firewall_data.name }}"
    name: "{{ firewall_data.name }}"
    name: "{{ firewall_data.name }}"
    name: "{{ firewall_data.name }}"
    name: "{{ firewall_data.name }}"

**Comment by mamercad** [comment]
Following the API is generally the way to go, and as mentioned, adding a Firewall by Droplet ID [is the way the API handles this](https://docs.digitalocean.com/reference/api/api-reference/#operation/add_firewall_droplets). That being said, we do take liberties at times -- for example, the Droplet module imbues "unique name" functionality which doesn't exist in DO, i.e., there's no rule that says a Droplet name must be unique. There's no reason that the Firewall module couldn't add a "droplet_names" parameter (it'd probably have to fail if there were more than one Droplet with the same name -- ambiguity when it comes to firewalls is bad 😄 ). I do like the idea, in general, of using names to refer to things -- adding this "unique name" functionality in every module makes sense for 2.x, I think.

Anyhow, since the module mimics the API, and there's a module for getting Droplet information (`digital_ocean_droplet_info`), I'm not sure there's anything actionable to do for this. If you like the idea of adding an (optional, but, mutually-exclusive "droplet_names" parameters), perhaps we close this issue and open a new "feature request" issue with this idea -- thoughts?

**Comment by tadeboro** [comment]
> Following the API is generally the way to go, and as mentioned, adding a Firewall by Droplet ID [is the way the API handles this](https://docs.digitalocean.com/reference/api/api-reference/#operation/add_firewall_droplets).

I must strongly disagree here. Ansible modules should mimic the API only if the API design is aligned with the common use cases. And this is clearly not the case here.

When dealing with VMs, it is quite common to specify firewalls/security groups at the instance creation time. And the DO collection (and the underlying API that modules use) make this task really painful. The playbook snippet I provided should be considered a hack and not something one would want to document as the right way of doing this. And to make matters even worse, the DO collection is the only one that forces users to perform this awkward dance. [AWS][], [OpenStack][], and [Hetzner][] collections all expose firewalls as part of the instance and not the other way around.

[AWS]: https://github.com/ansible-collections/amazon.aws/blob/715e72e7e9f7718338a78eca8da04c9963de0aa7/plugins/modules/ec2_instance.py#L114-L122
[OpenStack]: https://github.com/openstack/ansible-collections-openstack/blob/bbefa8c15605f76bdcc54f6468b07f5474b6a232/plugins/modules/server.py#L62-L68
[Hetzner]: https://github.com/ansible-collections/hetzner.hcloud/blob/51865c29ab306b60be88963e81687761260eae4b/plugins/modules/hcloud_server.py#L52-L56

> That being said, we do take liberties at times -- for example, the Droplet module imbues "unique name" functionality which doesn't exist in DO, i.e., there's no rule that says a Droplet name must be unique. There's no reason that the Firewall module couldn't add a "droplet_names" parameter (it'd probably have to fail if there were more than one Droplet with the same name -- ambiguity when it comes to firewalls is bad 😄 ). I do like the idea, in general, of using names to refer to things -- adding this "unique name" functionality in every module makes sense for 2.x, I think.

This will not solve the underlying issue because users will still need to use the firewall module when they in reality are trying to manage a droplet. Let me give another example that demonstrates this issue.

Let us assume that we have a droplet that has a few firewalls attached and we want to replace one of the firewalls. Currently, I need four tasks to perform this:

 1. The first task needs to retrieve information about the firewall I want to remove.
 2. The second task will remove the droplet ID from the result of the first task and then update the firewall with the new set of IDs.
 3. The third task will retrieve information about the first firewall we want to add.
 4. The fourth task will add the droplet ID to the result of the third task and then update the firewall with the updated set of IDs.

If the firewall names were exposed as an attribute of the droplet, we could just update our existing playbook, replace one name with another one, and perform the whole update in a single task.

> Anyhow, since the module mimics the API, and there's a module for getting Droplet information (`digital_ocean_droplet_info`), I'm not sure there's anything actionable to do for this. If you like the idea of adding an (optional, but, mutually-exclusive "droplet_name" parameter), perhaps we close this issue and open a new "feature request" issue with this idea -- thoughts?

To actually fix this for real, two things would need to happen:

 1. The firewall module would need to drop the `droplet_ids` parameter.
 2. The droplet module would need to gain a ` firewalls` parameter.

But since this would be a significant change in the API involving deprecation, this is not the easiest thing to do.

**Comment by mamercad** [comment]
> > Following the API is generally the way to go, and as mentioned, adding a Firewall by Droplet ID [is the way the API handles this](https://docs.digitalocean.com/reference/api/api-reference/#operation/add_firewall_droplets).
> 
> I must strongly disagree here. Ansible modules should mimic the API only if the API design is aligned with the common use cases. And this is clearly not the case here.
> 
> When dealing with VMs, it is quite common to specify firewalls/security groups at the instance creation time. And the DO collection (and the underlying API that modules use) make this task really painful. The playbook snippet I provided should be considered a hack and not something one would want to document as the right way of doing this. And to make matters even worse, the DO collection is the only one that forces users to perform this awkward dance. [AWS](https://github.com/ansible-collections/amazon.aws/blob/715e72e7e9f7718338a78eca8da04c9963de0aa7/plugins/modules/ec2_instance.py#L114-L122), [OpenStack](https://github.com/openstack/ansible-collections-openstack/blob/bbefa8c15605f76bdcc54f6468b07f5474b6a232/plugins/modules/server.py#L62-L68), and [Hetzner](https://github.com/ansible-collections/hetzner.hcloud/blob/51865c29ab306b60be88963e81687761260eae4b/plugins/modules/hcloud_server.py#L52-L56) collections all expose firewalls as part of the instance and not the other way around.

Fair enough, you make good points, and these are good examples.

> > That being said, we do take liberties at times -- for example, the Droplet module imbues "unique name" functionality which doesn't exist in DO, i.e., there's no rule that says a Droplet name must be unique. There's no reason that the Firewall module couldn't add a "droplet_names" parameter (it'd probably have to fail if there were more than one Droplet with the same name -- ambiguity when it comes to firewalls is bad 😄 ). I do like the idea, in general, of using names to refer to things -- adding this "unique name" functionality in every module makes sense for 2.x, I think.
> 
> This will not solve the underlying issue because users will still need to use the firewall module when they in reality are trying to manage a droplet. Let me give another example that demonstrates this issue.

I don't claim that this will solve the problem, I'm using the fact that we've implemented "unique name" in the Droplet module as an example of how we take liberties with the API and support behavior that doesn't exist in the DO Cloud / API. Again, you make good points -- and I agree with them -- that implementing "common use cases" is more important that keeping API parity.
 
> Let us assume that we have a droplet that has a few firewalls attached and we want to replace one of the firewalls. Currently, I need four tasks to perform this:
> 
> 1. The first task needs to retrieve information about the firewall I want to remove.
> 2. The second task will remove the droplet ID from the result of the first task and then update the firewall with the new set of IDs.
> 3. The third task will retrieve information about the first firewall we want to add.
> 4. The fourth task will add the droplet ID to the result of the third task and then update the firewall with the updated set of IDs.
> 
> If the firewall names were exposed as an attribute of the droplet, we could just update our existing playbook, replace one name with another one, and perform the whole update in a single task.
> 
> > Anyhow, since the module mimics the API, and there's a module for getting Droplet information (`digital_ocean_droplet_info`), I'm not sure there's anything actionable to do for this. If you like the idea of adding an (optional, but, mutually-exclusive "droplet_name" parameter), perhaps we close this issue and open a new "feature request" issue with this idea -- thoughts?
> 
> To actually fix this for real, two things would need to happen:
> 
> 1. The firewall module would need to drop the `droplet_ids` parameter.
> 2. The droplet module would need to gain a ` firewalls` parameter.
> 
> But since this would be a significant change in the API involving deprecation, this is not the easiest thing to do.

I'm not opposed to pursuing this, let's do it.
